services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./work:/home/work
    working_dir: /home/work
    command: jupyter lab --allow-root --port=8888 --ip=0.0.0.0 --NotebookApp.token=''
